services:
  gps-tracker:
    build:
      context: .
    image: gps-tracker-backend:local
    container_name: gps-tracker-backend
    restart: unless-stopped
    environment:
      PORT: "5013"
      HOST: "0.0.0.0"
      SERVER_TIMEZONE: "Asia/Colombo"
    ports:
      - "5013:5013/tcp"
